---
name: "Close stale issues and PRs"

# yamllint disable-line rule:truthy
on:
  schedule:
    - cron: "25 2 * * *"

jobs:
  default:
    uses: Hapag-Lloyd/Repository-Templates/.github/workflows/default_stale_callable.yml@1ae9a1d69c582281b4312e7ca65632adb32ddee8
    secrets: inherit
