---
name: PR opened

# yamllint disable-line rule:truthy
on:
  pull_request_target:
    types:
      - opened

jobs:
  default:
    # yamllint disable-line rule:line-length
    uses: Hapag-Lloyd/Repository-Templates/.github/workflows/default_welcome_message_callable.yml@1ae9a1d69c582281b4312e7ca65632adb32ddee8
    secrets: inherit
